version: '3.8'

services:
  userRegistration:
    image: user-registration
    build:
      context: .
    ports:
      - "8000:80"
    depends_on:
      - "db"

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - "5432:5432"
volumes:
  postgres_data:
