version: '3.8'
services:
  composer:
    image: composer:latest
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - .:/app
    restart: never
  
  phpunit:
    image: php:8.0-apache
    restart: never
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
  
  web:
    container_name: php-apache
    image: php:8.0-apache
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8080:80